### ISSUE TITLE
Change link css

### ISSUE THREAD

**Issue by maneeshalakshani** [Elzian-Agro/Agro#137]
The website's links are not clearly visible.   The link's colour change when hovered is not clear.

![link](https://user-images.githubusercontent.com/85009979/152298556-662af9bd-c947-48e2-a36a-2b97bcc02450.PNG)

So,
- Make links bold when hover
- Make links underline, when not hover

**Comment by pankajan05** [comment]
Currently, I don't find much problem with that and the underline is not suitable to the links. It makes the website not attractive. If you wish you can bold the things
