### ISSUE TITLE
The send message button is not visible as the button

### ISSUE THREAD

**Issue by pankajan05** [Elzian-Agro/Agro#31]
It must be correct in the home page and the contact us page.

![142970938-4a8f0ddf-5659-48d5-8fd6-e4f3dcec721a_LI](https://user-images.githubusercontent.com/37388848/142971179-fca2d491-5d28-4419-87cd-68f831cdac45.jpg)

**Comment by RimazRizkan** [comment]
I'll check on it

**Comment by Manoj0Marmat** [comment]
@RimazRizkan @pankajan05  can i help ? i'm beginner. need guidance
