### ISSUE TITLE
Product images needs to be add to Agro Eye and Home page

### ISSUE THREAD

**Issue by pankajan05** [Elzian-Agro/Agro#61]
You can find the images from the following link.
[https://photos.app.goo.gl/nQfQqjbkcNoGeQ12A](https://photos.app.goo.gl/nQfQqjbkcNoGeQ12A)

Add this image too.
![image](https://user-images.githubusercontent.com/37388848/147521263-34ff5a15-0011-4197-a80f-7b96f14f353f.png)

you can crop the images and you can use the images accordingly.

**Comment by Abdullah-Irfan-web** [comment]
hey @pankajan05 can you please tell me where i can have to add these images

**Comment by pankajan05** [comment]
It is needed to add to the home page and the catalog.html page.
