### ISSUE TITLE
Lets begin button on main page don't work

### ISSUE THREAD

**Issue by karanforprogram1** [Elzian-Agro/Agro#72]
The Lets Begin button on main page does nothing
![image](https://user-images.githubusercontent.com/83166715/148101146-6663bb9a-3d50-41df-91ed-070d4437bcbe.png)

**Comment by karanforprogram1** [comment]
Can you tell where do it needs to redirect, I can create a PR fixing it

**Comment by pankajan05** [comment]
Currently, It works correctly. It needs to scroll bottom.

**Comment by pankajan05** [comment]
Notify me button needs to redirect to the contact us page. so you can work on that.

**Comment by karanforprogram1** [comment]
Okay I will work on it
